### ISSUE TITLE
MTC_ContainerCamp/modules/kubernetes/kubernetes.md Install Permission Error

### ISSUE THREAD

**Issue by rajeshagadi** [Microsoft/MTC_ContainerCamp#30]
Rich,

Today I was able to create the cluster successfully. However, the command to install the Kubectl fails with lack of permission: Below is the command run.

![image](https://user-images.githubusercontent.com/17166696/32123664-eedc6912-bb19-11e7-8d05-dbb4da00b3f7.png)

Connection error while attempting to download client ([Errno 13] Permission denied: '/usr/local/bin/kubectl')

Please take look.

**Comment by richross** [comment]
The command as written works when in command line or PowerShell.  In Bash it fails because by default the user does not have permissions to write to this directory.  See this github issue for further information: https://github.com/Azure/azure-cli/issues/2558.  Based on this information, I would include the --install-location parameter for this step.  It is at least a better practice compared to the other options.
Are we forcing everyone to go the Bash route?  If not, then we may need 2 sets of instructions: one for bash and one for PS/CMD.  I lean towards 2 sets of instructions regardless as there may be reasons why bash is not an option during the lab.
Comments please :)

**Comment by richross** [comment]
Pull request #33 address this issue.  @rajeshagadi Please confirm and closeout if resolved.

**Comment by msftkru** [comment]
Certainly we have many different options in use for deployment (CMD, PS, WSL, Bash, Cloud Shell) and each has it's own nuances.  With the Jumpbox (Linux as default) being a setup requirement should we have the documentation assume that?  Looks like we are mentioning WSL and Bash as the assumed instructions.

**Comment by amazaheri** [comment]
My suggestion is to be agnostic as much as we can, for example I love to do everything from Mac or Bash on Windows and don't try the Jumpbox. if we want to keep the Jumpbox then yes we should assume that.

**Comment by amazaheri** [comment]
Can we close this issue?

**Comment by richross** [comment]
Core issue was addressed and included in the PR #38.  Additional comments about reorganizing included in issue #41.  Closing this issue.
